# site title
title: ciuji's blog

# user name or organization name
user: ciuji

# issue repository
repository: ciuji.github.io

# multi-author
authors: ciuji

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 8#9366d8b4f5aee7a38365fdc563b023b525310c0

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
